services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3017:3017"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - production-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.js
    ports:
      - "3107:3107"
    environment:
      - NODE_ENV=production
      - PORT=3107
      - DB_HOST=192.168.0.139
      - DB_USER=jitdhana
      - DB_PASSWORD=Jitdana@2025
      - DB_NAME=manufacturing_system
      - DB_PORT=3306
      - DB_TIMEZONE=+07:00
      - CORS_ORIGIN=*
    restart: unless-stopped
    networks:
      - production-network
    depends_on:
      - frontend

networks:
  production-network:
    driver: bridge
